apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: wealthops-ingress
  namespace: wealthops

spec:
  ingressClassName: nginx

  tls:
    - hosts:
       - wealthops.local
      secretName: wealthops-tls

  rules:
    - host: wealthops.local

      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wealthops
                port:
                  number: 5000